services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=growthbook
    volumes:
      - mongodata:/data/db
  growthbook:
    image: "growthbook/growthbook:latest"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - PORT=3000  # Force backend to use this port
      - MONGODB_URI=mongodb+srv://${DB_ROOT_USER}:${DB_ROOT_PASSWORD}@cluster0.sxumkcj.mongodb.net/growthbook?retryWrites=true&w=majority&authSource=admin
      - NODE_ENV=production
      - APP_ORIGIN=${APP_URL}  # Set this to your Render URL
      - API_HOST=${API_HOST}   # Should match APP_ORIGIN with :3100
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - uploads:/usr/local/src/app/packages/back-end/uploads
volumes:
  uploads:
  mongodata:
